# Generated by Django 5.0 on 2024-01-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='arr',
            field=models.JSONField(default=[]),
        ),
    ]
