# Generated by Django 5.0.3 on 2024-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scores',
            field=models.JSONField(default={'O': 0, 'X': 0}),
        ),
    ]
